version: '3.3'
services:
    registry:
        image: registry:2
        restart: always
        ports:
            - "5000:5000"
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        expose:
            # Opens port 5000 on the container
            - '5000'
        # Where our data will be persisted
        volumes:
            - registry-data:/data
        
    cache:
        image: redis:7.0.7
        restart: always
        ports:
            - "6379:6379"
        expose:
            # Opens port 6379 on the container
            - '6379'
        # Where our data will be persisted
        volumes:
            - cache-data:/data

    db:
        image: mysql:5.7.34
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - mysql-db:/var/lib/mysql

volumes:
    mysql-db:
    cache-data:
    registry-data:
